apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jankybank
  name: jankybank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jankybank
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jankybank
    spec:
      containers:
      - image: eurogig/jankybank@sha256:2a6558b676781dddf2a25bb7ebef91b24e90d2cdb8154a24eba809f90a8841da
        name: jankybank
        ports:
        - containerPort: 8080
        resources: {}
        securityContext:
          privileged: true
        envFrom:
        - secretRef:
            name: dbsecret
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: simpledeploy
  name: simpledeploy
spec:
  ports:
  - name: "38080"
    port: 38080
    protocol: TCP
    targetPort: 8080
  selector:
    app: jankybank
  type: NodePort
